server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    url: jdbc:mysql://10.134.162.22:3306/cat01?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接大小
      initial-size: 20
      # 最小空闲连接数
      min-idle: 20
      #最大连接数
      max-active: 200
      #查询超时时间
      query-timeout: 60000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      # 配置获取连接等待超时的时间
      max-wait: 60000
      ##配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ##配置一个连接在池中最小生存的时间，单位是毫秒
      min-victable-idle-time-millis: 300000
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/

#######
#  elasticsearch:
#    jest:
#      connection-timeout: 5000
#      uris:
#      - http://10.134.162.19:9200

# es配置
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: my-application
      cluster-nodes: 10.134.162.19:9300

##  mybatis配置
mybatis:
#  #实体类所做包
#  #type-aliases-package: learning.model
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml

  
#  通用mapper配置

mapper:
  identity: MYSQL
  before: false
  not-empty: true
  wrap-keyword: "`{0}`"  
  check-example-entity-class: true
  safe-delete: true
  safe-update: true
  normal: true

## log4j2 configuration
logging:
  config: classpath:log4j2.xml


    

    
    


